apiVersoin: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: skete/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: skete/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': . 
    - image: skete/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    
    
deploy:
  kubectl:
    manifests:
      - k8s/client-deplyment.yaml
      - k8s/server-deplyment.yaml
      - k8s/worker-deplyment.yaml
